"""baseline schema

Revision ID: 675056c8fffd
Revises: 
Create Date: 2026-07-20 17:53:09.251782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import octoforge_core.db.base


# revision identifiers, used by Alembic.
revision: str = '675056c8fffd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_fire_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.Column('last_fire_at', octoforge_core.db.base.UTCDateTime(), nullable=True),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_at', octoforge_core.db.base.UTCDateTime(), nullable=True),
    sa.Column('created_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cron_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_cron_jobs_due', ['enabled', 'next_fire_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cron_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('usage_notes', sa.String(), nullable=False),
    sa.Column('retention', sa.String(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('dialogs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('created_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel')
    )
    with op.batch_alter_table('dialogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dialogs_user_id'), ['user_id'], unique=False)

    op.create_table('instructions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('created_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'title')
    )
    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instructions_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_instructions_type'), ['type'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.Column('updated_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_user_id'), ['user_id'], unique=False)

    op.create_table('dataset_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_records_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_records_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dialog_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(), nullable=True),
    sa.Column('created_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dialog_id', 'seq')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_dialog_id'), ['dialog_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dialog_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('result_delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', octoforge_core.db.base.UTCDateTime(), nullable=False),
    sa.Column('started_at', octoforge_core.db.base.UTCDateTime(), nullable=True),
    sa.Column('finished_at', octoforge_core.db.base.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_dialog_id'), ['dialog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_dialog_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_dialog_id'))

    op.drop_table('messages')
    with op.batch_alter_table('dataset_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_records_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_records_dataset_id'))

    op.drop_table('dataset_records')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_user_id'))

    op.drop_table('memories')
    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instructions_type'))
        batch_op.drop_index(batch_op.f('ix_instructions_title'))

    op.drop_table('instructions')
    with op.batch_alter_table('dialogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dialogs_user_id'))

    op.drop_table('dialogs')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_owner_user_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('cron_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cron_jobs_user_id'))
        batch_op.drop_index('ix_cron_jobs_due')

    op.drop_table('cron_jobs')
    # ### end Alembic commands ###
