"""Storage ports for Telegram invites, referrals and member profiles."""

from typing import Protocol

from octoforge_telegram.invites.types import (
    Invite,
    MemberProfile,
    MemberProfileUpdate,
    ReferralClaim,
)


class MemberDirectory(Protocol):
    async def record(self, profile: MemberProfileUpdate) -> None: ...

    async def get(self, user_id: str) -> MemberProfile | None: ...

    async def list_all(self) -> list[MemberProfile]: ...


class ReferralStore(Protocol):
    async def code_of(self, owner_user_id: str) -> str: ...

    async def owner_of(self, code: str) -> str | None: ...

    async def record_claim(self, user_id: str, referrer_user_id: str, code: str) -> None: ...

    async def claim_of(self, user_id: str) -> ReferralClaim | None: ...

    async def claims(self) -> list[ReferralClaim]: ...


class InviteStore(Protocol):
    async def create(self, note: str) -> Invite: ...

    async def get_by_code(self, code: str) -> Invite | None: ...

    async def get_by_id(self, invite_id: str) -> Invite | None: ...

    async def claim(self, code: str, user_id: str) -> Invite: ...

    async def get_by_user(self, user_id: str) -> Invite | None: ...

    async def list_all(self) -> list[Invite]: ...

    async def revoke(self, invite_id: str) -> Invite: ...

    async def restore(self, invite_id: str) -> Invite: ...

    async def set_disabled_cron_jobs(self, invite_id: str, job_ids: tuple[str, ...]) -> None: ...
