"""Catalog, limit-gate and usage-ledger ports."""

from datetime import datetime
from typing import Protocol

from octoforge_core.tariffs.types import Tariff, TariffDefinition
from octoforge_core.tariffs.usage_types import LimitVerdict, UsageEvent, UsageTotals


class UsageRecorder(Protocol):
    async def record(self, event: UsageEvent) -> None: ...


class LimitGate(UsageRecorder, Protocol):
    async def enabled_features(self, user_id: str) -> frozenset[str] | None: ...

    async def allows(self, user_id: str, feature: str) -> bool: ...

    async def check_run_budget(self, user_id: str) -> LimitVerdict: ...

    async def max_cron_jobs(self, user_id: str) -> int | None: ...

    async def max_datasets(self, user_id: str) -> int | None: ...

    async def max_memory_chars(self, user_id: str) -> int | None: ...


class TariffStore(Protocol):
    async def put(self, definition: TariffDefinition) -> Tariff: ...

    async def list(self) -> list[Tariff]: ...

    async def delete(self, code: str) -> None: ...

    async def assign(self, user_id: str, code: str | None) -> None: ...

    async def tariff_for_user(self, user_id: str) -> Tariff | None: ...

    async def assignments(self) -> dict[str, str]: ...


class UsageMeter(Protocol):
    async def record(self, event: UsageEvent) -> None: ...

    async def totals_since(self, user_id: str, since: datetime) -> UsageTotals: ...
