"""Public FastAPI dependency facade."""

from octoforge_server.operator_deps import get_operator, require_admin
from octoforge_server.request_identity import (
    ACCESS_STATUS_HEADER,
    CHANNEL_HEADER,
    get_channel,
    get_external_id,
    get_user_id,
)
from octoforge_server.state_deps import (
    get_access_service,
    get_activation_notifier,
    get_admin_read_model,
    get_auth_gate,
    get_claim_repository,
    get_conversation_manager,
    get_cron_store,
    get_dialog_repository,
    get_exchange_repository,
    get_identity_store,
    get_instruction_service,
    get_known_features,
    get_limit_gate,
    get_media_service,
    get_secret_links,
    get_secret_store,
    get_settings,
    get_settings_store,
    get_summary_store,
    get_tariff_store,
    get_task_store,
    get_usage_meter,
    get_user_param_store,
)

__all__ = [
    "ACCESS_STATUS_HEADER",
    "CHANNEL_HEADER",
    "get_access_service",
    "get_activation_notifier",
    "get_admin_read_model",
    "get_auth_gate",
    "get_channel",
    "get_claim_repository",
    "get_conversation_manager",
    "get_cron_store",
    "get_dialog_repository",
    "get_exchange_repository",
    "get_external_id",
    "get_identity_store",
    "get_instruction_service",
    "get_known_features",
    "get_limit_gate",
    "get_media_service",
    "get_operator",
    "get_secret_links",
    "get_secret_store",
    "get_settings",
    "get_settings_store",
    "get_summary_store",
    "get_tariff_store",
    "get_task_store",
    "get_usage_meter",
    "get_user_id",
    "get_user_param_store",
    "require_admin",
]
