"""Persistence port for background tasks."""

from typing import Protocol

from octoforge_core.tasks.api import Task

TaskList = list[Task]


class TaskStore(Protocol):
    async def add(self, task: Task) -> None: ...

    async def get(self, task_id: str) -> Task: ...

    async def list(self, dialog_id: str) -> list[Task]: ...

    async def delete(self, task_id: str) -> None: ...

    async def delete_for_dialog(self, dialog_id: str) -> int: ...

    async def list_orphaned(self, dialog_id: str | None = None) -> TaskList: ...

    async def list_undelivered(self, dialog_id: str | None = None) -> TaskList: ...

    async def list_for_recovery(
        self,
        dialog_id: str | None = None,
    ) -> tuple[TaskList, TaskList]: ...

    async def mark_delivered(self, task_id: str) -> None: ...

    async def mark_done(self, task_id: str, result: str, *, delivered: bool = False) -> Task: ...

    async def mark_failed(self, task_id: str, error: str, *, delivered: bool = False) -> Task: ...

    async def mark_cancelled(self, task_id: str) -> Task: ...
