"""OctoForge agent core library."""

from octoforge_core.agent.control import LoopControl
from octoforge_core.agent.events import (
    AssistantMessage,
    Cancelled,
    Failed,
    Finished,
    IterationStarted,
    LoopEvent,
    ProcessCompleted,
    ProcessStarted,
    RetryScheduled,
    TextDelta,
    ToolCallCompleted,
    ToolCallFailed,
    ToolCallRequested,
)
from octoforge_core.agent.loop import AgentLoop
from octoforge_core.agent.prompts import PromptProvider
from octoforge_core.agent.router import MessageRouter
from octoforge_core.agent.runner import (
    ConversationEvent,
    ConversationManager,
    ConversationRunner,
    ManagerStores,
    OwnershipConfig,
    RunnerConfig,
    TaskOutcomeListener,
)
from octoforge_core.composition import (
    RunnerOptions,
    ToolLimits,
    ToolServices,
    ToolStores,
    build_agent_loop,
    build_collecting_sweeper,
    build_compactor,
    build_conversation_manager,
    build_cron_outcome_reporter,
    build_cron_scheduler,
    build_dataset_service,
    build_dataset_store,
    build_external_executor,
    build_instruction_service,
    build_instruction_store,
    build_llm_client,
    build_router,
    build_runner_config,
    build_summary_store,
    build_tool_registry,
)
from octoforge_core.config import EmbeddingConfig, LLMConfig
from octoforge_core.context.api import ContextCompactor, MessageArchive, SummaryStore
from octoforge_core.cron.api import CronStore, CronWaker, Scheduler
from octoforge_core.datasets.api import DatasetService, DatasetStore, DatasetVectorSearch
from octoforge_core.db.engine import (
    bootstrap_schema,
    create_engine,
    create_session_factory,
    init_db,
)
from octoforge_core.db.unit_of_work import UnitOfWork, outside_uow
from octoforge_core.dialogs.api import (
    ClaimRepository,
    DialogNotFoundError,
    DialogRepository,
    ExchangeRepository,
    MessageRepository,
)
from octoforge_core.domain import (
    Attachment,
    AttachmentKind,
    ChatMessage,
    Dialog,
    MessageKind,
    MessageRole,
    MessageSource,
    ToolCall,
)
from octoforge_core.errors import LLMResponseError
from octoforge_core.instructions.api import (
    InstructionService,
    InstructionStore,
    InstructionVectorSearch,
)
from octoforge_core.llm.embeddings import EmbeddingClient
from octoforge_core.llm.errors import (
    AuthError,
    ClientError,
    ContextOverflowError,
    ErrorKind,
    LLMError,
    ProviderInternalError,
    QuotaError,
    RateLimitError,
    TransportError,
)
from octoforge_core.llm.reranker import RerankerClient
from octoforge_core.llm.retry import RetryingLLMClient
from octoforge_core.llm.usage import Completion, Usage
from octoforge_core.memory.api import Memory
from octoforge_core.ports import LLMClient
from octoforge_core.search.api import SearchProvider
from octoforge_core.tasks.api import Task, TaskKind, TaskStatus
from octoforge_core.tasks.store import SqlAlchemyTaskStore, TaskStore
from octoforge_core.time import utc_now
from octoforge_core.tools.base import (
    TaskDeleteOutcome,
    TaskDeleter,
    TaskSpawner,
    Tool,
    ToolContext,
    ToolSpec,
)
from octoforge_core.tools.errors import (
    DuplicateToolError,
    ToolArgumentsError,
    ToolNotFoundError,
)
from octoforge_core.tools.registry import ToolRegistry

__all__ = [
    "AgentLoop",
    "AssistantMessage",
    "Attachment",
    "AttachmentKind",
    "AuthError",
    "Cancelled",
    "ChatMessage",
    "ClaimRepository",
    "ClientError",
    "Completion",
    "ContextCompactor",
    "ContextOverflowError",
    "ConversationEvent",
    "ConversationManager",
    "ConversationRunner",
    "CronStore",
    "CronWaker",
    "DatasetService",
    "DatasetStore",
    "DatasetVectorSearch",
    "Dialog",
    "DialogNotFoundError",
    "DialogRepository",
    "DuplicateToolError",
    "EmbeddingClient",
    "EmbeddingConfig",
    "ErrorKind",
    "ExchangeRepository",
    "Failed",
    "Finished",
    "InstructionService",
    "InstructionStore",
    "InstructionVectorSearch",
    "IterationStarted",
    "LLMClient",
    "LLMConfig",
    "LLMError",
    "LLMResponseError",
    "LoopControl",
    "LoopEvent",
    "ManagerStores",
    "Memory",
    "MessageArchive",
    "MessageKind",
    "MessageRepository",
    "MessageRole",
    "MessageRouter",
    "MessageSource",
    "OwnershipConfig",
    "ProcessCompleted",
    "ProcessStarted",
    "PromptProvider",
    "ProviderInternalError",
    "QuotaError",
    "RateLimitError",
    "RerankerClient",
    "RetryScheduled",
    "RetryingLLMClient",
    "RunnerConfig",
    "RunnerOptions",
    "Scheduler",
    "SearchProvider",
    "SqlAlchemyTaskStore",
    "SummaryStore",
    "Task",
    "TaskDeleteOutcome",
    "TaskDeleter",
    "TaskKind",
    "TaskOutcomeListener",
    "TaskSpawner",
    "TaskStatus",
    "TaskStore",
    "TextDelta",
    "Tool",
    "ToolArgumentsError",
    "ToolCall",
    "ToolCallCompleted",
    "ToolCallFailed",
    "ToolCallRequested",
    "ToolContext",
    "ToolLimits",
    "ToolNotFoundError",
    "ToolRegistry",
    "ToolServices",
    "ToolSpec",
    "ToolStores",
    "TransportError",
    "UnitOfWork",
    "Usage",
    "bootstrap_schema",
    "build_agent_loop",
    "build_collecting_sweeper",
    "build_compactor",
    "build_conversation_manager",
    "build_cron_outcome_reporter",
    "build_cron_scheduler",
    "build_dataset_service",
    "build_dataset_store",
    "build_external_executor",
    "build_instruction_service",
    "build_instruction_store",
    "build_llm_client",
    "build_router",
    "build_runner_config",
    "build_summary_store",
    "build_tool_registry",
    "create_engine",
    "create_session_factory",
    "init_db",
    "outside_uow",
    "utc_now",
]
