"""Stable interface for task-scoped response memory and reading tools.

Implementation lives in cohesive sibling modules; imports from this module
remain the supported seam for callers.
"""

from octoforge_core.net.response_find import ResponseFindTool
from octoforge_core.net.response_get import ResponseGetTool
from octoforge_core.net.response_models import (
    DEFAULT_BUDGET_MB,
    DEFAULT_GET_CHARS,
    DEFAULT_GET_MAX_CHARS,
    DEFAULT_MAX_RESPONSE_MB,
    MEGABYTE,
    NO_KEY_TEMPLATE,
    NOT_FOUND_TEMPLATE,
    REF_PREFIX,
    RENDER_IN_THREAD_CHARS,
    TEXT_HAS_NO_KEYS,
    DocumentDraft,
    DocumentHome,
    ResponseMemoryConfig,
    ResponseNotFoundError,
    StoredDocument,
    StoredResponse,
)
from octoforge_core.net.response_passport import (
    ESTIMATE_SAMPLE_CHARS,
    KILOBYTE,
    LARGE_TEXT_CHARS,
    MAX_LISTED_TEXTS,
    PREVIEW_CHARS,
    THOUSAND,
    dotted_get,
    estimate_tokens,
    render_document_passport,
)
from octoforge_core.net.response_store import RAM_LIFETIME_NOTE, ResponseMemory
from octoforge_core.net.response_tool_specs import (
    FIND_DEFAULT_AFTER,
    FIND_DEFAULT_BEFORE,
    FIND_DEFAULT_MATCHES,
    FIND_DESCRIPTION,
    FIND_MAX_MATCHES,
    FIND_NAME,
    FIND_SCHEMA,
    GET_DESCRIPTION,
    GET_NAME,
    GET_SCHEMA,
    MAX_PATTERN_CHARS,
    WINDOW_DEFAULT_AFTER,
    WINDOW_DEFAULT_BEFORE,
    WINDOW_DESCRIPTION,
    WINDOW_NAME,
    WINDOW_SCHEMA,
)
from octoforge_core.net.response_window import ResponseWindowTool

__all__ = [
    "DEFAULT_BUDGET_MB",
    "DEFAULT_GET_CHARS",
    "DEFAULT_GET_MAX_CHARS",
    "DEFAULT_MAX_RESPONSE_MB",
    "ESTIMATE_SAMPLE_CHARS",
    "FIND_DEFAULT_AFTER",
    "FIND_DEFAULT_BEFORE",
    "FIND_DEFAULT_MATCHES",
    "FIND_DESCRIPTION",
    "FIND_MAX_MATCHES",
    "FIND_NAME",
    "FIND_SCHEMA",
    "GET_DESCRIPTION",
    "GET_NAME",
    "GET_SCHEMA",
    "KILOBYTE",
    "LARGE_TEXT_CHARS",
    "MAX_LISTED_TEXTS",
    "MAX_PATTERN_CHARS",
    "MEGABYTE",
    "NOT_FOUND_TEMPLATE",
    "NO_KEY_TEMPLATE",
    "PREVIEW_CHARS",
    "RAM_LIFETIME_NOTE",
    "REF_PREFIX",
    "RENDER_IN_THREAD_CHARS",
    "TEXT_HAS_NO_KEYS",
    "THOUSAND",
    "WINDOW_DEFAULT_AFTER",
    "WINDOW_DEFAULT_BEFORE",
    "WINDOW_DESCRIPTION",
    "WINDOW_NAME",
    "WINDOW_SCHEMA",
    "DocumentDraft",
    "DocumentHome",
    "ResponseFindTool",
    "ResponseGetTool",
    "ResponseMemory",
    "ResponseMemoryConfig",
    "ResponseNotFoundError",
    "ResponseWindowTool",
    "StoredDocument",
    "StoredResponse",
    "dotted_get",
    "estimate_tokens",
    "render_document_passport",
]
